defaultTheme: "dark"
EnableThemeToggle: false
EnableSharingButtons: true
EnableGlobalLanguageMenu: false
backgroundImage: "/static/machinetop_background.jpg"
backgroundEffects: false
showPosts: false
ReadMoreText: false
fontAwesome: 
  all: true
ShowReadingTime: false
LastModDisplay: false
tags: false
logo:
  logoText: "headup.ws"
  logoCursorColor: "#ffffff"
social:
  - name: "blog"
    url: "https://blog.headup.ws"
    icon: fa-solid fa-blog
  - name: "apps"
    url: "/apps"
    icon: "fa-solid fa-star"
  - name: "github"
    url: "https://github.com/alsotoes"
  - name: "youtube"
    url: "https://youtube.com/@alsotoes"
  - name: "x-twitter"
    url: "https://x.com/alsotoes"
  - name: "Buy me a coffee"
    url: "https://www.buymeacoffee.com/alvaro.soto/"
    icon: fa-solid fa-coffee
  - name: "Linkedin"
    url: "https://www.linkedin.com/in/alvaro-soto-58564226/"
    icon: fa-brands fa-linkedin-in
  - name: "gravatar"
    url: "https://gravatar.com/alsotoes/"
    icon: fa-solid fa-user
footer:
  showVersion: false
  socialIcons: true
  author: false
  rss: false
  trademark: true
  copyright: true
  bottomText: [
    "Powered by <a href=\"http://gohugo.io\">Hugo</a>", 
    "with <a href=\"https://github.com/coolapso/hugo-theme-hello-4s3ti\">Hello-friend-4s3ti</a>",
  ]
